# Generated by Django 4.2.30 on 2026-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('hero_title', models.CharField(default="Hi, I'm [Your Name]", max_length=200)),
                ('hero_subtitle', models.CharField(default='I build things for the web.', max_length=300)),
                ('about_heading', models.CharField(default='About Me', max_length=200)),
                ('about_text', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback if no image uploaded', null=True)),
                ('description', models.TextField()),
                ('tech', models.CharField(max_length=250)),
                ('impact', models.CharField(max_length=250)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(default=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-percentage'],
            },
        ),
    ]
