# Generated by Django 4.2.30 on 2026-07-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_github_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.TextField(blank=True, default='', help_text='Cloudinary URL of uploaded CV'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
